import type { TablerIcon } from '@tabler/icons-react'
import {
  IconAlarm,
  IconAlertCircle,
  IconAlertTriangle,
  IconApple,
  IconArrowLeft,
  IconArrowUpRight,
  IconAward,
  IconBarbell,
  IconBasket,
  IconBed,
  IconBike,
  IconBolt,
  IconBone,
  IconBook,
  IconBooks,
  IconBottle,
  IconBrain,
  IconBriefcase,
  IconBrush,
  IconBuildingBank,
  IconBulb,
  IconCalendar,
  IconCalendarWeek,
  IconCamera,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconCheck,
  IconChevronRight,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconClockHour4,
  IconCloud,
  IconCloudFog,
  IconCoffee,
  IconCoin,
  IconConfetti,
  IconCreditCard,
  IconCrown,
  IconDental,
  IconDeviceLaptop,
  IconDiamond,
  IconDog,
  IconDroplet,
  IconEgg,
  IconEye,
  IconFeather,
  IconFlame,
  IconFocus2,
  IconGift,
  IconGlass,
  IconHeart,
  IconHeartHandshake,
  IconHistory,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconLayoutDashboard,
  IconLeaf,
  IconList,
  IconListCheck,
  IconLock,
  IconMap,
  IconMedal,
  IconMessage,
  IconMeteor,
  IconMicrophone,
  IconMicroscope,
  IconMist,
  IconMoon,
  IconMusic,
  IconNumber1,
  IconPalette,
  IconPencil,
  IconPill,
  IconPlant,
  IconPlayerPlay,
  IconPlayerPause,
  IconPlus,
  IconReceipt,
  IconRepeat,
  IconRocket,
  IconRuler,
  IconRun,
  IconSalad,
  IconSchool,
  IconSearch,
  IconSeedling,
  IconSettings,
  IconShape,
  IconSnowflake,
  IconSoup,
  IconSparkles,
  IconStar,
  IconStretching,
  IconSum,
  IconSun,
  IconSunrise,
  IconSwimming,
  IconTag,
  IconTarget,
  IconTelescope,
  IconTools,
  IconTrash,
  IconTrophy,
  IconUser,
  IconUsers,
  IconVacuumCleaner,
  IconWalk,
  IconWashMachine,
  IconWorld,
  IconX,
  IconYoga,
  IconZzz,
} from '@tabler/icons-react'

export const ICON_REGISTRY = {
  alarm: IconAlarm,
  alert: IconAlertCircle,
  warning: IconAlertTriangle,
  apple: IconApple,
  'arrow-left': IconArrowLeft,
  'arrow-up-right': IconArrowUpRight,
  award: IconAward,
  barbell: IconBarbell,
  basket: IconBasket,
  bed: IconBed,
  bike: IconBike,
  bolt: IconBolt,
  bone: IconBone,
  book: IconBook,
  books: IconBooks,
  bottle: IconBottle,
  brain: IconBrain,
  briefcase: IconBriefcase,
  brush: IconBrush,
  bank: IconBuildingBank,
  bulb: IconBulb,
  calendar: IconCalendar,
  'calendar-week': IconCalendarWeek,
  camera: IconCamera,
  'chart-bar': IconChartBar,
  'chart-line': IconChartLine,
  'chart-pie': IconChartPie,
  check: IconCheck,
  'chevron-right': IconChevronRight,
  'circle-check': IconCircleCheck,
  'circle-x': IconCircleX,
  clock: IconClock,
  timer: IconClockHour4,
  cloud: IconCloud,
  fog: IconCloudFog,
  coffee: IconCoffee,
  coin: IconCoin,
  confetti: IconConfetti,
  card: IconCreditCard,
  crown: IconCrown,
  dental: IconDental,
  laptop: IconDeviceLaptop,
  diamond: IconDiamond,
  dog: IconDog,
  water: IconDroplet,
  egg: IconEgg,
  eye: IconEye,
  feather: IconFeather,
  flame: IconFlame,
  focus: IconFocus2,
  gift: IconGift,
  glass: IconGlass,
  heart: IconHeart,
  handshake: IconHeartHandshake,
  history: IconHistory,
  home: IconHome,
  inbox: IconInbox,
  info: IconInfoCircle,
  dashboard: IconLayoutDashboard,
  leaf: IconLeaf,
  list: IconList,
  'list-check': IconListCheck,
  lock: IconLock,
  map: IconMap,
  medal: IconMedal,
  message: IconMessage,
  meteor: IconMeteor,
  microphone: IconMicrophone,
  microscope: IconMicroscope,
  mist: IconMist,
  moon: IconMoon,
  music: IconMusic,
  one: IconNumber1,
  palette: IconPalette,
  pencil: IconPencil,
  pill: IconPill,
  plant: IconPlant,
  play: IconPlayerPlay,
  pause: IconPlayerPause,
  plus: IconPlus,
  receipt: IconReceipt,
  repeat: IconRepeat,
  rocket: IconRocket,
  ruler: IconRuler,
  run: IconRun,
  salad: IconSalad,
  school: IconSchool,
  search: IconSearch,
  seedling: IconSeedling,
  settings: IconSettings,
  shapes: IconShape,
  snowflake: IconSnowflake,
  soup: IconSoup,
  sparkles: IconSparkles,
  star: IconStar,
  stretching: IconStretching,
  sum: IconSum,
  sun: IconSun,
  sunrise: IconSunrise,
  swim: IconSwimming,
  tag: IconTag,
  target: IconTarget,
  telescope: IconTelescope,
  tools: IconTools,
  trash: IconTrash,
  trophy: IconTrophy,
  user: IconUser,
  users: IconUsers,
  vacuum: IconVacuumCleaner,
  walk: IconWalk,
  laundry: IconWashMachine,
  world: IconWorld,
  x: IconX,
  yoga: IconYoga,
  sleep: IconZzz,
} as const satisfies Record<string, TablerIcon>

export type IconName = keyof typeof ICON_REGISTRY

export interface IconOption {
  name: IconName
  label: string
  group: 'Hareket' | 'Sağlık' | 'Odak' | 'Yaşam' | 'Sosyal' | 'Başarı'
}

export const ICON_OPTIONS: readonly IconOption[] = [
  { name: 'run', label: 'Koşu', group: 'Hareket' },
  { name: 'walk', label: 'Yürüyüş', group: 'Hareket' },
  { name: 'barbell', label: 'Ağırlık', group: 'Hareket' },
  { name: 'bike', label: 'Bisiklet', group: 'Hareket' },
  { name: 'swim', label: 'Yüzme', group: 'Hareket' },
  { name: 'stretching', label: 'Esneme', group: 'Hareket' },
  { name: 'yoga', label: 'Yoga', group: 'Hareket' },
  { name: 'bolt', label: 'Enerji', group: 'Hareket' },
  { name: 'target', label: 'Hedef', group: 'Hareket' },
  { name: 'heart', label: 'Kalp', group: 'Sağlık' },
  { name: 'water', label: 'Su', group: 'Sağlık' },
  { name: 'glass', label: 'Bardak', group: 'Sağlık' },
  { name: 'bottle', label: 'Şişe', group: 'Sağlık' },
  { name: 'apple', label: 'Elma', group: 'Sağlık' },
  { name: 'salad', label: 'Beslenme', group: 'Sağlık' },
  { name: 'pill', label: 'Vitamin', group: 'Sağlık' },
  { name: 'dental', label: 'Diş', group: 'Sağlık' },
  { name: 'sleep', label: 'Uyku', group: 'Sağlık' },
  { name: 'bed', label: 'Yatak', group: 'Sağlık' },
  { name: 'moon', label: 'Gece', group: 'Sağlık' },
  { name: 'sun', label: 'Güneş', group: 'Sağlık' },
  { name: 'sunrise', label: 'Gün doğumu', group: 'Sağlık' },
  { name: 'coffee', label: 'Kahve', group: 'Sağlık' },
  { name: 'egg', label: 'Kahvaltı', group: 'Sağlık' },
  { name: 'brain', label: 'Zihin', group: 'Odak' },
  { name: 'focus', label: 'Odak', group: 'Odak' },
  { name: 'timer', label: 'Sayaç', group: 'Odak' },
  { name: 'clock', label: 'Saat', group: 'Odak' },
  { name: 'book', label: 'Kitap', group: 'Odak' },
  { name: 'books', label: 'Kitaplar', group: 'Odak' },
  { name: 'school', label: 'Eğitim', group: 'Odak' },
  { name: 'laptop', label: 'Bilgisayar', group: 'Odak' },
  { name: 'pencil', label: 'Yazı', group: 'Odak' },
  { name: 'bulb', label: 'Fikir', group: 'Odak' },
  { name: 'microscope', label: 'Araştırma', group: 'Odak' },
  { name: 'telescope', label: 'Keşif', group: 'Odak' },
  { name: 'ruler', label: 'Ölçüm', group: 'Odak' },
  { name: 'calendar', label: 'Takvim', group: 'Odak' },
  { name: 'calendar-week', label: 'Hafta', group: 'Odak' },
  { name: 'list-check', label: 'Görevler', group: 'Odak' },
  { name: 'briefcase', label: 'İş', group: 'Odak' },
  { name: 'inbox', label: 'Gelen kutusu', group: 'Odak' },
  { name: 'home', label: 'Ev', group: 'Yaşam' },
  { name: 'vacuum', label: 'Temizlik', group: 'Yaşam' },
  { name: 'laundry', label: 'Çamaşır', group: 'Yaşam' },
  { name: 'basket', label: 'Sepet', group: 'Yaşam' },
  { name: 'trash', label: 'Çöp', group: 'Yaşam' },
  { name: 'plant', label: 'Bitki', group: 'Yaşam' },
  { name: 'seedling', label: 'Gelişim', group: 'Yaşam' },
  { name: 'leaf', label: 'Doğa', group: 'Yaşam' },
  { name: 'palette', label: 'Yaratıcılık', group: 'Yaşam' },
  { name: 'brush', label: 'Resim', group: 'Yaşam' },
  { name: 'camera', label: 'Fotoğraf', group: 'Yaşam' },
  { name: 'music', label: 'Müzik', group: 'Yaşam' },
  { name: 'microphone', label: 'Ses', group: 'Yaşam' },
  { name: 'map', label: 'Harita', group: 'Yaşam' },
  { name: 'world', label: 'Dünya', group: 'Yaşam' },
  { name: 'dog', label: 'Köpek', group: 'Sosyal' },
  { name: 'bone', label: 'Evcil dost', group: 'Sosyal' },
  { name: 'users', label: 'Topluluk', group: 'Sosyal' },
  { name: 'user', label: 'Kişi', group: 'Sosyal' },
  { name: 'message', label: 'Sohbet', group: 'Sosyal' },
  { name: 'handshake', label: 'Destek', group: 'Sosyal' },
  { name: 'gift', label: 'Hediye', group: 'Sosyal' },
  { name: 'confetti', label: 'Kutlama', group: 'Başarı' },
  { name: 'trophy', label: 'Kupa', group: 'Başarı' },
  { name: 'award', label: 'Ödül', group: 'Başarı' },
  { name: 'medal', label: 'Madalya', group: 'Başarı' },
  { name: 'crown', label: 'Taç', group: 'Başarı' },
  { name: 'diamond', label: 'Elmas', group: 'Başarı' },
  { name: 'star', label: 'Yıldız', group: 'Başarı' },
  { name: 'meteor', label: 'Meteor', group: 'Başarı' },
  { name: 'rocket', label: 'Roket', group: 'Başarı' },
  { name: 'flame', label: 'Alev', group: 'Başarı' },
  { name: 'sparkles', label: 'Parıltı', group: 'Başarı' },
  { name: 'coin', label: 'Para', group: 'Başarı' },
  { name: 'bank', label: 'Banka', group: 'Başarı' },
  { name: 'card', label: 'Kart', group: 'Başarı' },
  { name: 'receipt', label: 'Fiş', group: 'Başarı' },
  { name: 'chart-line', label: 'İlerleme', group: 'Başarı' },
]

const LEGACY_EMOJI_TO_ICON: Record<string, IconName> = {
  '🏃': 'run', '🚶': 'walk', '💪': 'barbell', '🏋️': 'barbell', '🏋': 'barbell',
  '🚴': 'bike', '🏊': 'swim', '🤸': 'stretching', '🧘': 'yoga', '💧': 'water',
  '🥤': 'glass', '🌊': 'water', '🐬': 'swim', '🤿': 'swim', '🐳': 'water',
  '❤️': 'heart', '❤': 'heart', '🫀': 'heart', '🥗': 'salad', '🥦': 'salad',
  '🍎': 'apple', '💊': 'pill', '🦷': 'dental', '😴': 'sleep', '💤': 'sleep',
  '🛌': 'bed', '🛏️': 'bed', '🌙': 'moon', '🌌': 'moon', '☀️': 'sun',
  '☀': 'sun', '🌤️': 'cloud', '🌤': 'cloud', '🌅': 'sunrise', '🌄': 'sunrise',
  '☕': 'coffee', '🍵': 'coffee', '🥛': 'glass', '🍳': 'egg', '🧠': 'brain',
  '🎯': 'target', '⏱️': 'timer', '⏱': 'timer', '⏰': 'alarm', '🍅': 'timer',
  '📖': 'book', '📚': 'books', '🎓': 'school', '💻': 'laptop', '✏️': 'pencil',
  '✍️': 'pencil', '✍': 'pencil', '💡': 'bulb', '🔬': 'microscope',
  '🔭': 'telescope', '📐': 'ruler', '🗺️': 'map', '🗓️': 'calendar',
  '📆': 'calendar', '📋': 'list-check', '📝': 'list-check', '💼': 'briefcase',
  '📥': 'inbox', '🏠': 'home', '🧹': 'vacuum', '🧺': 'laundry', '🗑️': 'trash',
  '🌱': 'seedling', '🌿': 'leaf', '🌳': 'plant', '🌺': 'plant', '🎨': 'palette',
  '🖌️': 'brush', '📷': 'camera', '🎬': 'camera', '🎵': 'music', '🎸': 'music',
  '🎹': 'music', '🎻': 'music', '🎙️': 'microphone', '🌍': 'world',
  '🐕': 'dog', '🦴': 'bone', '👥': 'users', '💬': 'message', '🤝': 'handshake',
  '🫂': 'users', '👋': 'user', '🙏': 'handshake', '🎉': 'confetti',
  '🥳': 'confetti', '🏆': 'trophy', '🎖️': 'award', '🏅': 'medal',
  '🥇': 'medal', '👑': 'crown', '💎': 'diamond', '⭐': 'star', '🌟': 'star',
  '🌠': 'meteor', '🚀': 'rocket', '🔥': 'flame', '✨': 'sparkles',
  '⚡': 'bolt', '✅': 'circle-check', '❄️': 'snowflake', '❄': 'snowflake',
  '🌫️': 'fog', '🌫': 'fog', '💰': 'coin', '💵': 'coin', '🪙': 'coin',
  '🏦': 'bank', '💳': 'card', '🧾': 'receipt', '📈': 'chart-line',
  '📊': 'chart-bar', '⚙️': 'settings', '⚙': 'settings', '🔒': 'lock',
  '🔍': 'search', '▶️': 'play', '▶': 'play',
}

export function isIconName(value: unknown): value is IconName {
  return typeof value === 'string' && value in ICON_REGISTRY
}

export function iconFromLegacyEmoji(value: unknown, fallback: IconName = 'sparkles'): IconName {
  if (isIconName(value)) return value
  if (typeof value !== 'string') return fallback
  return LEGACY_EMOJI_TO_ICON[value] ?? LEGACY_EMOJI_TO_ICON[value.replace(/\uFE0F/g, '')] ?? fallback
}
